config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :subjects, only: [:show, :index, :create] do
    # nested resource for posts
    resources :cards, only: [:show, :index,  :new, :create, :destroy]
  end
  root 'subjects#index'



end

app/models/ability.rb
class Ability
  include CanCan::Ability

  can :read, Subject, active: true, user_id: user.id

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :front, presence: true, uniqueness: true

    belongs_to :user
    belongs_to :subject

  def subject_name=(name)
    self.subject = Subject.find_or_create_by(name: name)
  end

  def random
    self.subject.cards.sample
  end

  def next
    current_cards = self.subject.cards
    current_cards.where("id > ?", id).first || current_cards.first
  end

  def previous
    current_cards = self.subject.cards
    current_cards.where("id < ?", id).last || current_cards.last
  end

end

app/models/subject.rb
class Subject < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :cards
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :subjects
  has_many :cards, through: :subjects


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @cards = Subject.find(params[:subject_id]).cards
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @cards}
    end
  end

  def show
    @subject = Subject.find(params[:subject_id])
    @card = (Subject.find(params[:subject_id])).cards.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @card}
    end
  end

  def card_data
    card = Card.find(params[:id])
    render json: card.to_json
  end

  def new
  end

  # def edit
  #   @card = Card.find(params[:id])
  #   respond_to do |format|
  #     format.html { render :edit }
  #     format.json { render json: @card}
  #   end
  # end

  def create
    card = Card.create(card_params)
    card.user_id = current_user.id
    card.save
    render json: card, status: 201
    # redirect_to new_card_path
  end

  def update
    @card = Card.find(params[:id])

    if @card.update(card_params)
      redirect_to subjects_path
    else
      render 'edit'
    end
  end

  def destroy
    @card = Card.find(params[:id]).destroy
    redirect_to subjects_path
  end

  private
    def card_params
      params.permit(:subject_id, :front, :back, :user_id)
    end

    def set_cards
      @card = Card.find(params[:id])
      @subject = Subject.find(params[:subject_id])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    @users = User.all
  end

  def create
    user = User.find_by(name: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to subjects_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_user_session_path
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @subjects = current_user.subjects
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @subjects}
    end
  end

  def show
    @subject = Subject.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @subject}
    end
  end

  def create
    subject = Subject.create(subject_params)
    subject.user_id = current_user.id
    subject.save
    render json: subject, status: 201
  end

  def new
  end

  def cards_index
    @subject = Subject.find(params[:id])
    @cards = @subject.cards
    render template: 'cards/index'
  end

  def cards
    @subject = Subject.find(params[:id])
    @card = Card.find(params[:card_id])
    render template: 'cards/show'
  end

  private
    def subject_params
      params.permit(:name, :user_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to subjects_path(@user)
    else
      flash[:message] = @user.errors.full_messages.uniq.join(', ')
      redirect_to new_card_path
    end
  end

  def show
    redirect_to new_user_session_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cards/_cards.html.erb
<div class="card_holder">
  <h2 id="front"><%= card.id.front %></h2>
  <h2 id="back"><%= card.id.back %></h2>
</div>

app/views/cards/_links.html.erb
<div class='links'>
<%= link_to = button_to('New Card', new_card_path, :method => :post) %>
<%= link_to = button_to('Edit Card', edit_card_path, :method => :get) %>
<%= link_to = button_to('Delete Card', card_path(@card), :method => :delete, data: {confirm: "Are you sure you want to delete this card?"}) %>
</div>

app/views/cards/_nav.html.erb
<ul class="navbar">
  <!-- <%= link_to 'All Subjects', subjects_path %> -->
  <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
</ul>

app/views/cards/edit.html.erb
<br>
<br>
<%= render 'nav' %>

<h2>Edit Card</h2>

<%= form_for @card do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
       <h2>There were some errors:</h2>
       <ul>
         <% @card.errors.full_messages.each do |m| %>
           <li><%= m %></li>
         <% end %>
       </ul>
     </div>
  <% end %>

      <div class="field<%= ' field_with_errors' if @card.errors[:front].any? %>">
        <%= f.label :front %><br>
        <%= f.text_area :front %>
      </div>


    <p>
      <%= f.label :back %><br>
      <%= f.text_area :back %>
    </p>

    <p>
      <%= f.submit %>
    </p>

    </div>
<% end %>

app/views/cards/index.html.erb
<br>
<br>
<%= render 'nav' %>
<h2 id="subject_name"></h2>
<div id="study_main">
<!-- <h2><% @cards.each do |c| %></h2>
    <% if c.user_id == current_user.id %>
      <div class="card_holder">
        <h2 class="front"><%= c.front %></h2>
        <h2 class="back"><%= c.back %></h>
      </div>
      <% end %>
  <% end %> -->
</div>
<br>
<!-- <button id="study_button">Study!</button> -->
<button id="next_button">Flip</button>
<button id="previous_button">Previous</button>
<button id="back_button">All Cards</button>
<button id="random_button">Random</button>
<button id="new_card_button">New Card</button>



<br>

app/views/cards/new.html.erb
<br>
<br>
<%= render 'nav' %>

<h2>Make a new card</h2>

<%= form_for :card, url: cards_path do |f| %>

  <%= f.label :subject %><br>
    <%= f.text_field :subject_name, list: "subjects_autocomplete" %>
    <br>
    <datalist id="subjects_autocomplete">
      <%= Subject.all.each do |subject| %>
        <option value="<%= subject.name %>">
      <% end %>
  </datalist>

  <div>
    <%= f.label :front %><br>
    <%= f.text_area :front %>
  </div>

  <p>
    <%= f.label :back %><br>
    <%= f.text_area :back %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/cards/show.html.erb
<br>
<br>

<%= render 'nav' %>

<h2><%=@subject.name %> cards</h2>

<div class="card_holder">
  <h2 class="front"><%= @card.front %></h2>
  <h2 class="back"><%= @card.back %></h2>
</div>
<br>
<br>
<br>

<script type="text/javascript" charset="utf-8">
$(function () {
  $(".js-next").on("click", function() {
    var nextId = parseInt($(".js-next").attr("data-id")) + 1;
    $.get("/cards/" + nextId + "/card_data", function(data) {
      $(".cardFront").text(data["front"]);
      $(".cardBack").text(data["back"]);
      // re-set the id to current on the link
      $(".js-next").attr("data-id", data["id"]);
    });
  });
});
</script>

<%= render 'links' %>

app/views/layouts/_nav.html.erb
<ul class="navbar">
  <%= link_to = button_to('Sign Out', destroy_user_session_path, :method => :delete) %>
  <%= link_to 'All Subjects', subjects_path %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <footer>


    <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
    <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
  </footer>
</html>

app/views/subjects/_buttons.html.erb
<button id="new_subject_button" class="phase0">New Subject</button>

<!-- shown in both -->
<button id="back_button" class="phase1">Back</button>

<!-- shown at getCards -->
<button id="study_button" class="phase2">Study!</button>
<button id="new_card_button" class="phase2">New</button>

<!-- shown at getCard -->
<button id="next_button" class="phase3">Next</button>
<button id="previous_button" class="phase3">Previous</button>
<button id="random_button" class="phase3">Random</button>

app/views/subjects/_links.html.erb
<%= link_to = button_to('Edit Card', edit_card_path, :method => :post) %>
<%= link_to = button_to('Subjects', subjects_path) %>

app/views/subjects/_nav.html.erb
<ul class="navbar1">
  <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
</ul>

app/views/subjects/index.html.erb
<div id="header_div">
</div>
<br>
<%= render 'buttons' %>
<div id="main">
</div>
<br>
<%= render 'nav' %>

app/views/subjects/new.html.erb
<br>
<br>
<%= render 'nav' %>

<%= form_for :subject, url: subjects_path do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
  <%= f.user_id :current_user.id %>
      <%= f.submit %>
    <p>
<% end %>

app/views/subjects/show.html.erb
<br>
<br>
<%= render 'nav' %>

<h2><%="#{current_user.email}"%>'s subjects</h2>
<ul>
  <h2><%= link_to "#{@subject.name}", subject_cards_path(@subject) %></h2>
_______________________________________________

</ul>
<%= link_to = button_to('New Card', new_card_path) %>